ddocker-publish-update-dockerfile #4 Annotations 1 error build failed 1 minute ago in 11s 2s Current runner version: '2.322.0' Operating System Runner Image Runner Image Provisioner GITHUB_TOKEN Permissions Secret source: Actions Prepare workflow directory Prepare all required actions Getting action download info Download action repository 'actions/checkout@v4' (SHA:11bd71901bbe5b1630ceea73d27597364c9af683) Download action repository 'sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20' (SHA:59acb6260d9c0ba8f4a2f9d9b48431a222b68e20) Download action repository 'docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226' (SHA:f95db51fddba0c2d1ec667646a06c2ce06100226) Download action repository 'docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d' (SHA:343f7c4344506bcbf9b4de18042ae17996df046d) Download action repository 'docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934' (SHA:96383f45573cb7f253c731d3b3ab81c87ef81934) Download action repository 'docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09' (SHA:0565240e2d4ab88bba5387d719585280857ece09) Complete job name: build 0s Run actions/checkout@v4 Syncing repository: ROMLIANY/RL Getting Git version info Temporarily overriding HOME='/home/runner/work/_temp/fb5833e5-7372-44d9-a91b-abfa68233a20' before making global git config changes Adding repository directory to the temporary git global config as a safe directory /usr/bin/git config --global --add safe.directory /home/runner/work/RL/RL Deleting the contents of '/home/runner/work/RL/RL' Initializing the repository Disabling automatic garbage collection Setting up auth Fetching the repository Determining the checkout info /usr/bin/git sparse-checkout disable /usr/bin/git config --local --unset-all extensions.worktreeConfig Checking out the ref /usr/bin/git log -1 --format=%H d359f1428febd769046b0101ad7665da6cda9247 0s Run sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20 Run #!/bin/bash INFO: Downloading bootstrap version 'v2.2.4' of cosign to verify version to be installed...       https://github.com/sigstore/cosign/releases/download/v2.2.4/cosign-linux-amd64 INFO: bootstrap version successfully verified and matches requested version so nothing else to do Run echo "$HOME/.cosign" >> $GITHUB_PATH 4s Run docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 Docker info Buildx version Creating a new builder instance Booting builder Inspect builder BuildKit version 0s Run docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d Logging into ghcr.io... Login Succeeded! 0s Run docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 Context info Processing images input Processing tags input Processing flavor input Docker image version Docker tags Docker labels JSON output Bake file definition 1s Run docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 GitHub Actions runtime token ACs Docker info Proxy configuration Buildx version /usr/bin/docker buildx build --cache-from type=gha --cache-to type=gha,mode=max --iidfile /tmp/docker-actions-toolkit-xyb2F2/iidfile --label org.opencontainers.image.created=2025-02-27T19:29:23.527Z --label org.opencontainers.image.description= --label org.opencontainers.image.licenses= --label org.opencontainers.image.revision=d359f1428febd769046b0101ad7665da6cda9247 --label org.opencontainers.image.source=https://github.com/ROMLIANY/RL --label org.opencontainers.image.title=RL --label org.opencontainers.image.url=https://github.com/ROMLIANY/RL --label org.opencontainers.image.version=main --tag ghcr.io/romliany/rl:main --metadata-file /tmp/docker-actions-toolkit-xyb2F2/metadata-file --push .
ERROR: failed to solve: failed to read dockerfile: open Dockerfile: no such file or directory
Error: buildx failed with: ERROR: failed to solve: failed to read dockerfile: open Dockerfile: no such file or directory
0s
0s
Post job cleanup.
Removing temp folder /tmp/docker-actions-toolkit-xyb2F2
0s
Post job cleanup.
/usr/bin/docker logout ghcr.io
Removing login credentials for ghcr.io
0s
Post job cleanup.
Removing builder
Cleaning up certificates
0s
Post job cleanup.
/usr/bin/git version
git version 2.48.1
Temporarily overriding HOME='/home/runner/work/_temp/a074ad0b-931c-4b24-8368-53f557f7327a' before making global git config changes
Adding repository directory to the temporary git global config as a safe directory
/usr/bin/git config --global --add safe.directory /home/runner/work/RL/RL
/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
http.https://github.com/.extraheader
/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"
0s
Cleaning up orphan processesocker-publish-update-dockerfile #4
Annotations
1 error
build
failed 1 minute ago in 11s
2s
Current runner version: '2.322.0'
Operating System
Runner Image
Runner Image Provisioner
GITHUB_TOKEN Permissions
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v4' (SHA:11bd71901bbe5b1630ceea73d27597364c9af683)
Download action repository 'sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20' (SHA:59acb6260d9c0ba8f4a2f9d9b48431a222b68e20)
Download action repository 'docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226' (SHA:f95db51fddba0c2d1ec667646a06c2ce06100226)
Download action repository 'docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d' (SHA:343f7c4344506bcbf9b4de18042ae17996df046d)
Download action repository 'docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934' (SHA:96383f45573cb7f253c731d3b3ab81c87ef81934)
Download action repository 'docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09' (SHA:0565240e2d4ab88bba5387d719585280857ece09)
Complete job name: build
0s
Run actions/checkout@v4
Syncing repository: ROMLIANY/RL
Getting Git version info
Temporarily overriding HOME='/home/runner/work/_temp/fb5833e5-7372-44d9-a91b-abfa68233a20' before making global git config changes
Adding repository directory to the temporary git global config as a safe directory
/usr/bin/git config --global --add safe.directory /home/runner/work/RL/RL
Deleting the contents of '/home/runner/work/RL/RL'
Initializing the repository
Disabling automatic garbage collection
Setting up auth
Fetching the repository
Determining the checkout info
/usr/bin/git sparse-checkout disable
/usr/bin/git config --local --unset-all extensions.worktreeConfig
Checking out the ref
/usr/bin/git log -1 --format=%H
d359f1428febd769046b0101ad7665da6cda9247
0s
Run sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20
Run #!/bin/bash
INFO: Downloading bootstrap version 'v2.2.4' of cosign to verify version to be installed...
      https://github.com/sigstore/cosign/releases/download/v2.2.4/cosign-linux-amd64
INFO: bootstrap version successfully verified and matches requested version so nothing else to do
Run echo "$HOME/.cosign" >> $GITHUB_PATH
4s
Run docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226
Docker info
Buildx version
Creating a new builder instance
Booting builder
Inspect builder
BuildKit version
0s
Run docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
Logging into ghcr.io...
Login Succeeded!
0s
Run docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934
Context info
Processing images input
Processing tags input
Processing flavor input
Docker image version
Docker tags
Docker labels
JSON output
Bake file definition
1s
Run docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09
GitHub Actions runtime token ACs
Docker info
Proxy configuration
Buildx version
/usr/bin/docker buildx build --cache-from type=gha --cache-to type=gha,mode=max --iidfile /tmp/docker-actions-toolkit-xyb2F2/iidfile --label org.opencontainers.image.created=2025-02-27T19:29:23.527Z --label org.opencontainers.image.description= --label org.opencontainers.image.licenses= --label org.opencontainers.image.revision=d359f1428febd769046b0101ad7665da6cda9247 --label org.opencontainers.image.source=https://github.com/ROMLIANY/RL --label org.opencontainers.image.title=RL --label org.opencontainers.image.url=https://github.com/ROMLIANY/RL --label org.opencontainers.image.version=main --tag ghcr.io/romliany/rl:main --metadata-file /tmp/docker-actions-toolkit-xyb2F2/metadata-file --push .

ERROR: failed to solve: failed to read dockerfile: open Dockerfile: no such file or directory
Error: buildx failed with: ERROR: failed to solve: failed to read dockerfile: open Dockerfile: no such file or directory
0s
0s
Post job cleanup.
Removing temp folder /tmp/docker-actions-toolkit-xyb2F2
0s
Post job cleanup.
/usr/bin/docker logout ghcr.io
Removing login credentials for ghcr.io
0s
Post job cleanup.
Removing builder
Cleaning up certificates
0s
Post job cleanup.
/usr/bin/git version
git version 2.48.1
Temporarily overriding HOME='/home/runner/work/_temp/a074ad0b-931c-4b24-8368-53f557f7327a' before making global git config changes
Adding repository directory to the temporary git global config as a safe directory
/usr/bin/git config --global --add safe.directory /home/runner/work/RL/RL
/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
http.https://github.com/.extraheader
/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"
0s
Cleaning up orphan processes